plugins:
  - jekyll-remote-theme
  - jekyll-asciidoc
  - mermaid
keep_files:
  - images
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: ./
remote_theme: pages-themes/cayman@v0.2.0
title: M2X
description: An interface definition for communication between peripherals and automated guided vehicles.