image::./assets/imgs/m2x_logo_colored.svg[width=50%,align="center"]

== M2X - Interface for communication between automated guided vehicles (AGVs) and intralogistics systems in the AGV environment
Version 0.1.1, October 2024

== Official M2X Documentation

The latest official documentation can be found on the https://m2x-project.github.io/m2x/[GitHub page]

== Introduction
The M2X project is being developed as part of Industrial Collective Research between the Chair of Material Handling and Warehousing at TU Dortmund University and the Fraunhofer Institute for Material Flow and Logistics IML (associated partner). The VDMA (German, Verband Deutscher Maschinen- und Anlagenbau e. V.) and various partners from industry support the project. The aim is to design universally applicable interfaces for communication between the master control (MC) via automated guided vehicles (AGVs) or autonomous mobile robots (AMRs) and industrial environment (load handling stations, order generation, peripherals, AGV to X).  Proposed changes to the interface are to be posted in the GitHub repository (https://github.com/M2X-Project/m2x). They will be jointly evaluated by the working group and, if the decision is positive, adopted in a new version.
Warehousing is increasingly relying on AGVs and AMRs. However, the implementation of such automated guided vehicle systems (AGVS) is both time-consuming and cost-intensive and poses a challenge for both large companies and SMEs (small and medium sized companies). Interface definitions such as VDA 5050 standardize the connection between a master controller and AGVs and enable the cost-efficient use of heterogeneous fleets through interoperability. The M2X project, aims to reduce integration costs through further standardization in the AGVS context. Further necessary interfaces are identified and described using easily applicable, generally valid models. M2X enables companies to integrate automation quickly and cost-effectively. This gives companies a sustainable competitive advantage and secures their future on the market.
The project and the associated requirements are defined and iteratively adapted in close communication with our partners. The interfaces identified so far for M2X are as follows:
* Load handling station,
* Order generation,
* Peripherals (doors, elevators, (signal) lamps and traffic lights),
* AGV to AGV or attachment.

=== Current status and participating at M2X
The next steps, will deal with the load handling and order generation interfaces. The working group meets at regular meetings to discuss the new content and publish it.
New content will be pre-released in the private repository.
News updates on content or meetings can be found at the LinkedIn page https://www.linkedin.com/showcase/m2x-project 

== Build a local pdf version of the documentation

* Navigate with a terminal to the cloned repository
* Execute the following command to build the pdf version of the documentation
+
[source,shell]
----
asciidoctor -r asciidoctor-diagram -r asciidoctor-pdf -b pdf -D ./pdf index.adoc
----
* The "index.pdf" can be found in the created "pdf" directory

== Local GitHub Pages

To start the GitHub pages locally, execute the following command:

[source,shell]
----
bundle exec jekyll serve
----

=== Prerequisites
* Install Ruby: https://www.ruby-lang.org/de/documentation/installation/
* Install AsciiDoc: https://asciidoctor.org/
* Install Jekyll: https://jekyllrb.com/
+
[source,shell]
----
git clone https://github.com/M2X-Project/m2x.git
----
* Navigate to the repository 
+
[source,shell]
----
cd m2x
----
* Install Jekyll dependencies
+
[source,shell]
----
bundle install
----
* Start the Jekyll server
+
[source,shell]
----
bundle exec jekyll serve
----